name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout the repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2️⃣ Setup Node.js (Node 20+ required)
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      # 3️⃣ Install dependencies
      - run: yarn install --frozen-lockfile

      # 4️⃣ Run semantic-release
      - run: yarn release
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Write app version to .env.production
        run: echo "NEXT_PUBLIC_APP_VERSION=${{ steps.semantic.outputs.new_release_version }}" > .env.production
